export const typesToSpanish = {
  accounting: 'contabilidad',
  airport: 'aeropuerto',
  amusement_park: 'parque de atracciones',
  aquarium: 'acuario',
  art_gallery: 'galería de arte',
  atm: 'cajero automático',
  bakery: 'panadería',
  bank: 'banco',
  bar: 'bar',
  beauty_salon: 'salón de belleza',
  bicycle_store: 'tienda de bicicletas',
  book_store: 'librería',
  bowling_alley: 'bolera',
  bus_station: 'estación de autobuses',
  cafe: 'cafetería',
  campground: 'campamento',
  car_dealer: 'concesionario de coches',
  car_rental: 'alquiler de coches',
  car_repair: 'reparación de coches',
  car_wash: 'lavado de coches',
  casino: 'casino',
  cemetery: 'cementerio',
  church: 'iglesia',
  city_hall: 'ayuntamiento',
  clothing_store: 'tienda de ropa',
  convenience_store: 'tienda de conveniencia',
  courthouse: 'juzgado',
  dentist: 'dentista',
  department_store: 'tienda por departamentos',
  doctor: 'doctor',
  drugstore: 'farmacia',
  electrician: 'electricista',
  electronics_store: 'tienda de electrónica',
  embassy: 'embajada',
  fire_station: 'estación de bomberos',
  florist: 'florería',
  funeral_home: 'funeraria',
  furniture_store: 'tienda de muebles',
  gas_station: 'gasolinera',
  gym: 'gimnasio',
  hair_care: 'cuidado del cabello',
  hardware_store: 'ferretería',
  hindu_temple: 'templo hindú',
  home_goods_store: 'tienda de artículos para el hogar',
  hospital: 'hospital',
  insurance_agency: 'agencia de seguros',
  jewelry_store: 'joyería',
  laundry: 'lavandería',
  lawyer: 'abogado',
  library: 'biblioteca',
  light_rail_station: 'estación de tren ligero',
  liquor_store: 'tienda de licores',
  local_government_office: 'oficina de gobierno local',
  locksmith: 'cerrajero',
  lodging: 'alojamiento',
  meal_delivery: 'entrega de comidas',
  meal_takeaway: 'comida para llevar',
  mosque: 'mezquita',
  movie_rental: 'alquiler de películas',
  movie_theater: 'cine',
  moving_company: 'empresa de mudanzas',
  museum: 'museo',
  night_club: 'club nocturno',
  painter: 'pintor',
  park: 'parque',
  parking: 'parkeo',
  pet_store: 'tienda de mascotas',
  pharmacy: 'farmacia',
  physiotherapist: 'fisioterapeuta',
  plumber: 'fontanero',
  police: 'policía',
  post_office: 'oficina de correos',
  primary_school: 'escuela primaria',
  real_estate_agency: 'agencia inmobiliaria',
  restaurant: 'restaurante',
  roofing_contractor: 'contratista de techos',
  rv_park: 'parque de autocaravanas',
  school: 'escuela',
  secondary_school: 'escuela secundaria',
  shoe_store: 'tienda de zapatos',
  shopping_mall: 'centro comercial',
  spa: 'spa',
  stadium: 'estadio',
  store: 'tienda',
  subway_station: 'estación de metro',
  supermarket: 'supermercado',
  synagogue: 'synagogue',
  taxi_stand: 'taxi_stand',
  tourist_attraction: 'atracción turistica',
  train_station: 'estación de tren',
  transit_station: 'estación de tránsito',
  travel_agency: 'agencia de viaje',
  university: 'universidad',
  veterinary_care: 'veterinaria',
  zoo: 'zoológico',
};
